version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db/dev/databases.sql:/docker-entrypoint-initdb.d/1-dev-database.sql
      - ./db/dev/roles.sql:/docker-entrypoint-initdb.d/2-dev-roles.sql